# Generated by Django 4.2.1 on 2023-05-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposrelacion',
            name='nombre',
            field=models.CharField(default='sin nombre', max_length=50),
            preserve_default=False,
        ),
    ]
